"@context":

ontologies:

  ## EFO

  - id: efo
    preferredPrefix: EFO
    title: Experimental Factor Ontology
    uri: http://www.ebi.ac.uk/efo
    description: "The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for external projects such as the NHGRI GWAS catalogue. It combines parts of several biological ontologies, such as anatomy, disease and chemical compounds. The scope of EFO is to support the annotation, analysis and visualization of data handled by many groups at the EBI and as the core ontology for the Centre for Therapeutic Validation (CTTV)"
    homepage: http://www.ebi.ac.uk/efo
    mailing_list: efo-users@lists.sourceforge.net
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
      - http://www.ebi.ac.uk/efo/alternative_term
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.ebi.ac.uk/efo/EFO_
    reasoner: OWL2
    oboSlims: false
    ontology_purl: http://www.ebi.ac.uk/efo/efo.owl

  ## overide for mondo

  - id: mondo
    ontology_purl: http://purl.obolibrary.org/obo/mondo.obo

  - id: ordo
    preferredPrefix: ORDO
    description: "The Orphanet Rare Disease ontology (ORDO) is jointly developed by Orphanet and the EBI to provide a structured vocabulary for rare diseases capturing relationships between diseases, genes and other relevant features which will form a useful resource for the computational analysis of rare diseases.
                  It derived from the Orphanet database (www.orpha.net ) , a multilingual database dedicated to rare diseases populated from literature and validated by international experts.
                  It integrates a nosology (classification of rare diseases), relationships (gene-disease relations, epiemological data) and connections with other terminologies (MeSH, UMLS, MedDRA),databases (OMIM, UniProtKB, HGNC, ensembl, Reactome, IUPHAR, Geantlas) or classifications (ICD10)."
    title: Orphanet Rare Disease Ontolog
    uri: http://www.orpha.net/ontology/orphanet.owl
    definition_property:
      - http://www.ebi.ac.uk/efo/definition
    synonym_property:
      - http://www.ebi.ac.uk/efo/alternative_term
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    base_uri:
      - http://www.orpha.net/ORDO/Orphanet_
    reasoner: OWL2
    oboSlims: false
    ontology_purl : http://www.orphadata.org/data/ORDO/ordo_orphanet.owl
